package httpctx

import (
	"go-archetype/internal/domain/auth"
	"go-archetype/internal/infrastructure/logging"

	"github.com/gofiber/fiber/v2"
	"github.com/sirupsen/logrus"
)

const loggerKey = "logger"

// Set stores request-scoped logger into Fiber context.
func Set(c *fiber.Ctx, logger *logrus.Entry) {
	c.Locals(loggerKey, logger)
}

// Get retrieves request-scoped logger or fallback.
func Get(c *fiber.Ctx, fallback *logrus.Entry) *logrus.Entry {
	if v := c.Locals(loggerKey); v != nil {
		if entry, ok := v.(*logrus.Entry); ok {
			return entry
		}
	}
	return fallback
}

// EnrichRequestID adds request id to a logger.
func EnrichRequestID(base *logrus.Entry, c *fiber.Ctx) *logrus.Entry {
	return base.WithFields(logging.Field("request_id", GetRequestID(c)))
}

// EnrichMeta adds request metadata to a logger.
func EnrichMeta(base *logrus.Entry, c *fiber.Ctx, latency int64) *logrus.Entry {
	return base.WithFields(logging.Fields(map[string]any{
		"method":     c.Method(),
		"path":       c.Path(),
		"ip":         c.IP(),
		"latency_ms": latency,
	}))
}

// EnrichUserInfo adds user info to a logger.
func EnrichUserInfo(base *logrus.Entry, c *fiber.Ctx) *logrus.Entry {
	if v := c.Locals("user"); v != nil {
		if claims, ok := v.(*auth.CustomClaims); ok {
			return base.WithFields(logging.Fields(map[string]any{
				"user_id": claims.Subject,
				"roles":   claims.Roles,
			}))
		}
	}
	return base
}

// GetRequestID reads request id generated by fiber middleware.
func GetRequestID(c *fiber.Ctx) string {
	if v := c.Locals("requestid"); v != nil {
		if id, ok := v.(string); ok {
			return id
		}
	}
	return ""
}
